# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "cbbeb5705ce55f1a315cc3a533d6cc0a"
name = "challenges-app"
application_url = "https://headers-addresses-wool-moderator.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "challenges-store.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_discounts"

[auth]
redirect_urls = [
  "https://headers-addresses-wool-moderator.trycloudflare.com/auth/callback",
  "https://headers-addresses-wool-moderator.trycloudflare.com/auth/shopify/callback",
  "https://headers-addresses-wool-moderator.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
